scorecard:
  # Setting a global scorecard option
  output: json
  plugins:
    # basic tests configured to test CRs
    - basic:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml"
    # olm tests configured to test CRs
    - olm:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_helmrepo_cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-helm-repo-operator/3.5.0/ibm-helm-repo-operator.v3.5.0.clusterserviceversion.yaml"
