apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helm-repo-index
  annotations:
    kubernetes.io/ingress.class: "ibm-icp-management"
    icp.management.ibm.com/rewrite-target: "/charts/index.yaml"
  labels:
    app: "helm-repo"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/name: "helm-repo"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  rules:
  - http:
      paths:
      - path: /helm-repo/charts/index.yaml
        backend:
          serviceName: helm-repo
          servicePort: 3001
