apiVersion: v1
appVersion: 4.1.0.0-000000
description: Internal Helm repository for ICP
keywords:
- IcpClusterResource
- Commercial
- ICP
- IKS
- ICPRHOCP
- Operations
- amd64
- ppc64le
- s390x
kubeVersion: '>=1.11.0'
tillerVersion: '>=2.16.1'
name: helm-repo
version: 3.6.1
