# arch: ""
auditService:
  config:
    enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/opencloudio/icp-audit-service@sha256:24a220374c39652f8b031637d852995bfaec5be2601f9e4c41eb1925531f466d
  name: icp-audit-service
  resources:
    limits:
      cpu: 200m
      memory: 250Mi
    requests:
      cpu: 200m
      memory: 250Mi
helmrepo:
  WLP_Creds:
    oidcClientId: WLP_CLIENT_ID
    oidcClientSecret: WLP_CLIENT_SECRET
    oidcName: platform-oidc-credentials
    redirectURL: http://localhost:3001/auth/liberty/callback
  env:
    CHARTS_REPO_NAME: local-charts
    CLUSTER_CA_DOMAIN: mycluster
    CLUSTER_PORT: 443
    PROXY_ROUTE: helm-repo
  image:
    name: helm-repo
    pullPolicy: IfNotPresent
    repository: quay.io/opencloudio/icp-helm-repo@sha256:bc95dc9703c0d26ad3af1004bbe4b236781ebd84082df430108948897dfabfe2
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
  volumeMounts:
    repoAssetsMountPath: /home/node/app/assets
    repoAssetsName: repo-assets
mongo:
  clientcertssecret: icp-mongodb-client-cert
  clustercertssecret: mongodb-root-ca-cert
  host: mongodb
  password:
    key: password
    secret: icp-mongodb-admin
  port: 27017
  username:
    key: user
    secret: icp-mongodb-admin
replicaCount: 1
runAsUser: 65534
tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Exists
- key: CriticalAddonsOnly
  operator: Exists
