# arch: ""
auditService:
  config:
    enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/opencloudio/icp-audit-service@sha256:a649814564039ee923cb503720e9c5e87c20b3c340f06c48660490aeaed04d5a
  name: icp-audit-service
  resources:
    limits:
      cpu: 200m
      memory: 250Mi
    requests:
      cpu: 200m
      memory: 250Mi
helmrepo:
  WLP_Creds:
    oidcClientId: WLP_CLIENT_ID
    oidcClientSecret: WLP_CLIENT_SECRET
    oidcName: platform-oidc-credentials
    redirectURL: http://localhost:3001/auth/liberty/callback
  env:
    CHARTS_REPO_NAME: local-charts
    PROXY_ROUTE: helm-repo
  image:
    name: helm-repo
    pullPolicy: IfNotPresent
    repository: quay.io/opencloudio/icp-helm-repo@sha256:048bd56d93928c0e6dc1e0a89d9bc6e62a04d67795371acd69b207d4f36cbdc7
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
  volumeMounts:
    repoAssetsMountPath: /home/node/app/assets
    repoAssetsName: repo-assets
mongo:
  clientcertssecret: icp-mongodb-client-cert
  clustercertssecret: mongodb-root-ca-cert
  host: mongodb
  password:
    key: password
    secret: icp-mongodb-admin
  port: 27017
  username:
    key: user
    secret: icp-mongodb-admin
replicaCount: 1
runAsUser: 65534
tolerations:
- effect: NoSchedule
  key: dedicated
  operator: Exists
- key: CriticalAddonsOnly
  operator: Exists
