apiVersion: operator.ibm.com/v1
kind: HelmRepo
metadata:
  name: helm-repo
spec:
  auditService:
    config:
      enabled: true
    image:
      imageRegistry: quay.io/opencloudio
      pullPolicy: IfNotPresent
      repository: icp-audit-service
      tag: 3.4.0
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 200m
        memory: 250Mi
  helmrepo:
    image:
      imageRegistry: quay.io/opencloudio
      pullPolicy: IfNotPresent
      repository: icp-helm-repo
      tag: 3.3.0
    resources:
      limits:
        cpu: 100m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
  replicaCount: 1
