channels:
- currentCSV: ibm-helm-repo-operator.v3.6.1
  name: dev
- currentCSV: ibm-helm-repo-operator.v3.6.1
  name: beta
- currentCSV: ibm-helm-repo-operator.v3.6.1
  name: stable-v1
defaultChannel: stable-v1
packageName: ibm-helm-repo-operator-app
